name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  build-mode: Debug # Release | Debug

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]

    steps:
      # Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build "./PandoraPlus.sln" --configuration ${{ env.build-mode }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pandora.Behaviour.Engine
          path: |
            ./PandoraPlus/bin/${{ env.build-mode }}/net7.0-windows
