name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  build-mode: Debug # Release | Debug
  # Explicit cache location to cache only nuget dependencies for this project.
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]

    steps:
      # Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: .Net Cache
        uses: actions/cache@v4
        with:
          # - Specify the same as `NUGET_PACKAGES`
          path: |
            ${{ github.workspace }}/.nuget/packages
            ${{ github.workspace }}/PandoraPlus/obj
            ${{ github.workspace }}/third_party/HKX2-Library/HKX2 WPF/obj
            ${{ github.workspace }}/third_party/XML-Cake/XML Cake/obj

          key: nuget-${{ runner.os }}-${{ matrix.dotnet-version }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Build
        run: dotnet build "./PandoraPlus.sln" --configuration ${{ env.build-mode }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pandora.Behaviour.Engine
          path: |
            ./PandoraPlus/bin/${{ env.build-mode }}/net7.0-windows
