name: Publish Self-Contained Builds

on:
  workflow_run:
    workflows: [build & tests & release]
    types: [completed]

env:
  DOTNET_VERSION: "9.0.x"
  PROFILE: Release # Release | Debug

jobs:
  publish:
    permissions:
      contents: write # Required for creating releases
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # Windows targets
          - rid: win-x64
            runner: windows-latest
            output-dir: Output.Win-x64
          - rid: win-x86
            runner: windows-latest
            output-dir: Output.Win-x86
          - rid: win-arm64
            runner: windows-latest
            output-dir: Output.Win-Arm64

          # Linux targets
          - rid: linux-x64
            runner: windows-latest
            output-dir: Output.Linux-x64
          - rid: linux-arm
            runner: windows-latest
            output-dir: Output.Linux-Arm
          - rid: linux-arm64
            runner: windows-latest
            output-dir: Output.Linux-Arm64
          - rid: linux-musl-x64
            runner: windows-latest
            output-dir: Output.Linux-Musl-x64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Get Latest Tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          fallback: 0.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # NOTE: When attempting to build with `Pandora+.sln` during `PublishSingleFile`, an error occurs, so specify exe project.
      # - err msg: Publishing to a single file is only supported for executable applications.
      - name: Publish Self-Contained
        run: |
          dotnet publish "./Pandora Behaviour Engine/Pandora Behaviour Engine.csproj" \
            -c ${{ env.PROFILE }} \
            -r ${{ matrix.rid }} \
            -o "${{ github.workspace }}/${{ matrix.output-dir }}" \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:IncludeAllContentForSelfExtract=true

      - name: Zip and Release
        uses: ./.github/actions/zip-and-release
        with:
          title: Pandora Behaviour Engine ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          output-dir: ${{ matrix.output-dir }}
          zip-path: "${{ matrix.output-dir }}/Pandora_Behaviour_Engine_${{ steps.latesttag.outputs.tag }}_${{ matrix.rid }}_net.zip"
