name: build & tests & release

on:
  push:
    tags:
      - "v*.*.*"

env:
  DOTNET_VERSION: "9.0.x"
  PROFILE: Release # Release | Debug
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # Since env cannot be specified in composite action, specify cache dir individually.

jobs:
  build:
    permissions:
      contents: write # Required for creating releases
    runs-on: windows-latest

    steps:
      # Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set output paths
        id: set_paths
        shell: pwsh
        run: |
          $output_dir='${{ github.workspace }}/Pandora Behaviour Engine/bin/${{ env.PROFILE }}/net9.0'
          $zip_file_name='Pandora_Behaviour_Engine_${{ github.ref_name }}.zip'
          $zip_dir='${{ github.workspace }}/Output'

          echo "output_dir=$output_dir" >> $env:GITHUB_OUTPUT
          $zip_path="$zip_dir/$zip_file_name"
          echo "zip_path=$zip_path" >> $env:GITHUB_OUTPUT

      - name: Build & Test -> Upload a Build Artifact
        uses: ./.github/actions/build-and-test
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          configuration: ${{ env.PROFILE }}
          solution-path: "./Pandora+.sln"
          output-dir: ${{ steps.set_paths.outputs.output_dir }}

      - name: Zip and Release
        uses: ./.github/actions/zip-and-release
        with:
          title: Pandora Behaviour Engine ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          output-dir: ${{ steps.set_paths.outputs.output_dir }}
          zip-path: ${{ steps.set_paths.outputs.zip_path }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    permissions:
      contents: write # Required for creating releases
    runs-on: ${{ matrix.runner }}
    needs: build

    strategy:
      matrix:
        include:
          # Windows targets
          - rid: win-x64
            runner: windows-latest
            output-dir: Output.Win-x64
          - rid: win-x86
            runner: windows-latest
            output-dir: Output.Win-x86
          - rid: win-arm64
            runner: windows-latest
            output-dir: Output.Win-Arm64

          # Linux targets
          - rid: linux-x64
            runner: windows-latest
            output-dir: Output.Linux-x64
          - rid: linux-arm
            runner: windows-latest
            output-dir: Output.Linux-Arm
          - rid: linux-arm64
            runner: windows-latest
            output-dir: Output.Linux-Arm64
          - rid: linux-musl-x64
            runner: windows-latest
            output-dir: Output.Linux-Musl-x64

    steps:
      # Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Publish Self-Contained
        shell: pwsh
        run: |
          dotnet publish "./Pandora Behaviour Engine/Pandora Behaviour Engine.csproj" `
            -c ${{ env.PROFILE }} `
            -r ${{ matrix.rid }} `
            -o "${{ github.workspace }}/${{ matrix.output-dir }}" `
            --self-contained true `
            /p:PublishSingleFile=true `
            /p:IncludeAllContentForSelfExtract=true

      - name: Zip and Release
        uses: ./.github/actions/zip-and-release
        with:
          # NOTE: The title is not provided here, so it will append to the existing release.
          tag: ${{ github.ref_name }}
          output-dir: ${{ matrix.output-dir }}
          zip-path: "${{ matrix.output-dir }}/Pandora_Behaviour_Engine_${{ github.ref_name }}_${{ matrix.rid }}_net.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
